export const GAME_CONFIG = {
  // Canvas
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 200,

  // Dino
  DINO_WIDTH: 44,
  DINO_HEIGHT: 47,
  DINO_DUCK_HEIGHT: 30,
  DINO_X: 50,
  GROUND_Y: 150,

  // Physics
  GRAVITY: 0.6,
  JUMP_VELOCITY: -13,

  // Game
  INITIAL_SPEED: 6,
  MAX_SPEED: 15,
  SPEED_INCREMENT: 0.001,
  MIN_OBSTACLE_INTERVAL: 800,
  MAX_OBSTACLE_INTERVAL: 2000,

  // Obstacles
  CACTUS_SMALL_WIDTH: 17,
  CACTUS_SMALL_HEIGHT: 35,
  CACTUS_LARGE_WIDTH: 25,
  CACTUS_LARGE_HEIGHT: 50,
  BIRD_WIDTH: 46,
  BIRD_HEIGHT: 30,

  // Score
  SCORE_PER_FRAME: 0.15,

  // Colors
  COLOR_DINO: '#ffffff',
  COLOR_GROUND: '#ffffff',
  COLOR_OBSTACLE: '#ffffff',
  COLOR_SKY: '#030030',
  COLOR_CLOUD: 'rgba(255, 255, 255, 0.3)',
} as const;
