spring:
  application:
    name: trycatch
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: io.ssafy.trycatch.domain
  configuration:
    map-underscore-to-camel-case: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 1800000      # 30분
  refresh-token-validity: 604800000   # 7일

gpt:
  api:
    url: ${GMS_BACK_BASE_URL}
    key: ${GMS_API_KEY}
    model: gpt-5-mini

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    io.ssafy: debug

server:
  port: 8081