spring:
  application:
    name: trycatch
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: false

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 86400000      # 24시간
  refresh-token-validity: 604800000   # 7일

gpt:
  api:
    url: ${GMS_BASE_URL}
    key: ${GMS_API_KEY}
    model: ${GMS_API_MODEL}

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    io.ssafy: debug

server:
  port: 8081